export declare function appendJournal(input: {
    tenantId: string;
    scope: string;
    taskRequestId: string;
    taskPlanId: string;
    taskStepId: string;
    checkpoint: string;
    effectPhase: string;
    dependencyId?: string | null;
    resourceLocator?: Record<string, unknown> | null;
    payloadHash?: string | null;
    journalPayload?: Record<string, unknown>;
    idempotencyKey: string;
    traceId: string;
    occurredAt?: string;
}): Promise<void>;
export declare function createCompensationCapsule(input: {
    tenantId: string;
    scope: string;
    taskRequestId: string;
    taskPlanId: string;
    taskStepId: string;
    sideEffectClass: string;
    idempotencyKey: string;
    targetDependency: string;
    compensatorId: string;
    compensatorVersion: string;
    resourceLocator: Record<string, unknown>;
    requestPayloadHash: string;
    preconditionSnapshot: Record<string, unknown>;
    fingerprintAtExecution: string;
    committedResourceId?: string | null;
    responseHandle?: string | null;
    revision?: string | null;
    capsulePayload: Record<string, unknown>;
    traceId: string;
}): Promise<string>;
export declare function getCompensationCapsule(capsuleId: string): Promise<Record<string, unknown> | null>;
export declare function getJournalEntries(taskStepId: string, maxCursor?: number): Promise<Record<string, unknown>[]>;
