// AUTO-GENERATED by GateMaster — DO NOT EDIT MANUALLY
// Rule: 禁止空洞填充行
// Rule Key: host-rule-447a64a64385
// Enforcement: must
// Scope: session / session_only
//
// 这个 Hook 干啥的：
// - 挂载点：after_file_write（文件写入后检查内容）
// - 触发条件：taskType 是 writing/review，或者 operation 是写/编辑小说章节
// - 检查逻辑：扫描变更的 .md / .txt 文件内容，如果包含类似：
//   "X没有回答"、"X没说话"、"没有回应"、"没有吭声"、"沉默不语"
//   就 REJECT，提示删除或在该沉默前后三行内补充暗线/情绪转折。

import type { GateContext, HookResult, RuleHook } from "./types";

export const hook: RuleHook = {
  id: "hook_host_rule_447a64a64385",
  rule_id: "4af53703-1845-4081-b1fd-33812f8b7448",
  rule_key: "host-rule-447a64a64385",
  mount_points: ["after_file_write"],

  shouldRun(context: GateContext): boolean {
    // IF 撰写小说章节 THEN MUST NOT 插入无意义的空洞填充行
    // applies_to: coding, review
    return (
      context.taskType === "writing" ||
      context.taskType === "review" ||
      context.operation === "write_novel_chapter" ||
      context.operation === "edit_chapter"
    );
  },

  async run(context: GateContext): Promise<HookResult> {
    const changedFiles = await context.getChangedFiles();
    const proseFiles = changedFiles.filter(
      (file) => file.endsWith(".md") || file.endsWith(".txt")
    );

    if (proseFiles.length === 0) {
      return { action: "PASS" };
    }

    // 空洞填充行模式：X没有回答 / X没说话 / 没有回应 / 没有吭声 / 沉默不语
    const hollowPatterns = [
      /.{0,20}没有回答.{0,20}/,
      /.{0,20}没说话.{0,20}/,
      /.{0,20}没有回应.{0,20}/,
      /.{0,20}没有吭声.{0,20}/,
      /.{0,20}沉默不语.{0,20}/
    ];

    for (const file of proseFiles) {
      try {
        const content = await context.readFile(file);
        const lines = content.split("\n");
        for (let i = 0; i < lines.length; i++) {
          const line = lines[i];
          for (const pattern of hollowPatterns) {
            if (pattern.test(line)) {
              return {
                action: "REJECT",
                reason: `检测到空洞填充行：文件 ${file} 第 ${i + 1} 行 "${line.trim()}"`,
                retry_hint: "请删除该填充行，或在该沉默前后三行内补充暗线、情绪转折或环境描写，让读者感知到其目的。",
                rule_id: "4af53703-1845-4081-b1fd-33812f8b7448",
                rule_key: "host-rule-447a64a64385"
              };
            }
          }
        }
      } catch {
        // 忽略无法读取的文件
      }
    }

    return { action: "PASS" };
  }
};
