// AUTO-GENERATED by GateMaster — DO NOT EDIT MANUALLY
// Rule: A项目专属规则
// Rule Key: scope-test-project-a
// Enforcement: must
// Scope: project / project_reusable

import type { GateContext, HookResult, RuleHook } from "./types";

export const hook: RuleHook = {
  id: "hook_scope_test_project_a",
  rule_id: "2d5f2267-139a-42e9-91b2-7b238ded119b",
  rule_key: "scope-test-project-a",
  mount_points: ["before_task_complete"],

  shouldRun(context: GateContext): boolean {
    // IF 操作发生在 project-a THEN MUST 使用 A 项目配置
    // Trigger: task_type 为 execution 且当前项目为 project-a
    return context.taskType === "execution" && context.projectId === "project-a";
  },

  async run(context: GateContext): Promise<HookResult> {
    // 再次确认作用域，防止 shouldRun 被绕过
    if (context.projectId !== "project-a") {
      return {
        action: "REJECT",
        reason: "当前操作未发生在 project-a，违反 A项目专属规则",
        retry_hint: "请在 project-a 项目上下文中执行该操作",
        rule_id: "2d5f2267-139a-42e9-91b2-7b238ded119b",
        rule_key: "scope-test-project-a"
      };
    }

    // 检查是否使用了 A 项目配置
    try {
      const configRaw = await context.readFile(".trae/project.json");
      const config = JSON.parse(configRaw);
      if (config.project_id !== "project-a") {
        throw new Error("project_id mismatch");
      }
    } catch {
      return {
        action: "REJECT",
        reason: "未找到或未正确使用 A 项目配置（.trae/project.json 中 project_id 必须为 project-a）",
        retry_hint: '请在项目根目录创建 .trae/project.json 并设置 { "project_id": "project-a" }',
        rule_id: "2d5f2267-139a-42e9-91b2-7b238ded119b",
        rule_key: "scope-test-project-a"
      };
    }

    return { action: "PASS" };
  }
};
