#!/usr/bin/env node
/**
 * _lib.mjs — trae hook 共享工具库
 * AUTO-GENERATED by GateMaster
 */

import fs from "fs";
import path from "path";

export async function readStdin() {
  let input = "";
  for await (const chunk of process.stdin) { input += chunk; }
  if (input.charCodeAt(0) === 0xFEFF) { input = input.slice(1); }
  return input;
}

export function parseContext(input) {
  const trimmed = input.trim();
  if (!trimmed) return null;
  try { return JSON.parse(trimmed); } catch { return null; }
}

export function getCwd(context) {
  return context?.cwd || process.env.TRAE_PROJECT_DIR || process.env.CLAUDE_PROJECT_DIR || process.cwd();
}

export function readProjectConfig(context) {
  const cwd = getCwd(context);
  try { return JSON.parse(fs.readFileSync(path.join(cwd, ".trae", "project.json"), "utf-8")); } catch { return null; }
}

export function outputResult(result, traeEvent) {
  if (result.action === "REJECT") {
    const reason = result.reason || "Hook rejected";
    const additionalContext = (result.suggestions || []).join("\n");
    process.stderr.write(reason);
    let output;
    if (traeEvent === "PreToolUse") {
      output = { hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: reason, additionalContext } };
    } else if (traeEvent === "Stop") {
      output = { decision: "block", reason: additionalContext || reason };
    } else if (traeEvent === "UserPromptSubmit") {
      output = { decision: "block", reason, hookSpecificOutput: { hookEventName: "UserPromptSubmit", additionalContext } };
    } else {
      output = { decision: "block", reason, hookSpecificOutput: { hookEventName: traeEvent, additionalContext } };
    }
    process.stdout.write(JSON.stringify(output));
    process.exit(2);
  } else {
    if (result.message) process.stdout.write(result.message);
    process.exit(0);
  }
}

export function runHook(shouldRun, run, traeEvent) {
  // 内部处理 async，避免顶层 await 问题
  (async () => {
    try {
      const input = await readStdin();
      const context = parseContext(input);
      if (!context) process.exit(0);
      if (!shouldRun(context)) process.exit(0);
      const result = run(context);
      outputResult(result, traeEvent);
    } catch (err) {
      process.stderr.write(`Hook error: ${err.message}\n`);
      process.exit(0);
    }
  })();
}